name: pylops_test
channels:
  - defaults
  - conda-forge
  - numba
  - pytorch
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - scipy=1.14.1
  - pytorch>=1.2.0
  - cpuonly
  - jax
  - pyfftw
  - pywavelets
  - sympy
  - matplotlib
  - ipython
  - pytest
  - Sphinx
  - numpydoc
  - numba
  - icc_rt
  - pre-commit
  - autopep8
  - isort
  - black
  - pip:
    - devito
    - dtcwt
    - scikit-fmm
    - spgl1
    - pytest-runner
    - setuptools_scm
    - pydata-sphinx-theme
    - sphinx-gallery
    - nbsphinx
    - sphinxemoji
    - image
    - flake8
    - mypy
