name: PyLops Testing (CuPy)

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment and Install dependencies and pylops
        run: |
          python3 -m venv .venv-pylops
          # write install scripts
          cat << 'EOF' > pylops_tests.sh
          #!/bin/bash
          PYTHON=.venv-pylops/bin/python3
          PIP=.venv-pylops/bin/pip
          ls $PYTHON
          ls $PIP
          EOF
          srun --account=yuxilab -n 1 -N 1 --gres=gpu:L40S:1 bash pylops_tests.sh
      - name: Tests with pytest 
        run: |
          export CUPY_PYLOPS=1; export TEST_CUPY_PYLOPS=1; 
          echo "done!"
          # source pylopsvenv/bin/activate 
          # pytest
